app = "therpy-bot-clean"
primary_region = "ams"

[build]

[env]
PORT = "8080"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
grace_period = "1m0s"
interval = "1m0s"
method = "GET"
path = "/"  # Make sure your app responds to this
protocol = "http"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024