# fly.toml app configuration file for full Maya bot

app = "maya-therapy-bot"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  PYTHON_VERSION = "3.10"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  # Increased timeout for heavy ML processing
  [[http_service.checks]]
    interval = "30s"
    grace_period = "10s"
    method = "GET"
    path = "/api/health"
    protocol = "http"
    timeout = "15s"

[processes]
  app = "uvicorn main:app --host 0.0.0.0 --port 8080 --workers 1"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048  # Increased memory for ML models

# Auto-scale configuration for handling audio processing loads
[http_service.concurrency]
  type = "requests"
  hard_limit = 10
  soft_limit = 5